# === JavaBindings.cmake ===
# Configurable variables (cached)
# FIXME: hardcoded (use find_program() ?)
set(JEXTRACT_EXECUTABLE "/usr/share/jextract-22/bin/jextract"
    CACHE FILEPATH "Path to jextract")

set(MVEC_PUBLIC_HEADER "${CMAKE_CURRENT_SOURCE_DIR}/src/cmake_project_name_original_case/Mvec.h")

# Find Java (javac/jar)
find_package(Java COMPONENTS Development REQUIRED)
if (NOT EXISTS ${JEXTRACT_EXECUTABLE})
  message(FATAL_ERROR "jextract not found: ${JEXTRACT_EXECUTABLE}")
endif()

# Java build directories
set(JAVA_BUILD_DIR ${CMAKE_CURRENT_BINARY_DIR}/java)
# sources generated by jextract
set(JAVA_GEN_DIR   ${JAVA_BUILD_DIR}/generated)
# class complitation outdir FIXME: move ?
set(JAVA_OUT_DIR   ${JAVA_BUILD_DIR}/out)
file(MAKE_DIRECTORY ${JAVA_GEN_DIR})
file(MAKE_DIRECTORY ${JAVA_OUT_DIR})

# jextract: generates .java sources from flat 'extern C' cmake_project_name_original_case/Mvec.h
add_custom_command(
  OUTPUT ${JAVA_GEN_DIR}/.stamp
  COMMAND ${CMAKE_COMMAND} -E echo "Running jextract…"
  COMMAND ${CMAKE_COMMAND} -E make_directory ${JAVA_GEN_DIR}
  COMMAND ${JEXTRACT_EXECUTABLE}
          -t org.garamon.cmake_project_name_original_case
          -l :$<TARGET_FILE:cmake_project_name_original_case>
          --output ${JAVA_GEN_DIR}
          ${MVEC_PUBLIC_HEADER}
  COMMAND ${CMAKE_COMMAND} -E touch ${JAVA_GEN_DIR}/.stamp
  DEPENDS cmake_project_name_original_case ${MVEC_PUBLIC_HEADER}
)
add_custom_target(jextract_bindings ALL DEPENDS ${JAVA_GEN_DIR}/.stamp)

# javac: compiles to ${JAVA_OUT_DIR}
add_custom_command(
  OUTPUT ${JAVA_OUT_DIR}/.stamp
  COMMAND ${CMAKE_COMMAND} -E echo "Compiling Java…"
  COMMAND "${Java_JAVAC_EXECUTABLE}"
          --source-path "${JAVA_GEN_DIR}"
          -cp "${JAVA_GEN_DIR}"
          -d "${JAVA_OUT_DIR}"
          "${JAVA_GEN_DIR}/org/garamon/cmake_project_name_original_case/Mvec_h.java"
  COMMAND ${CMAKE_COMMAND} -E touch ${JAVA_OUT_DIR}/.stamp
  DEPENDS jextract_bindings
)
add_custom_target(javac_bindings ALL DEPENDS ${JAVA_OUT_DIR}/.stamp)

# FIXME: JAR
if (Java_JAR_EXECUTABLE)
  add_custom_target(cmake_project_name_original_case_jar
    COMMAND ${CMAKE_COMMAND} -E echo "Packaging JAR…"
    COMMAND ${Java_JAR_EXECUTABLE} cf ${JAVA_BUILD_DIR}/cmake_project_name_original_case.jar -C ${JAVA_OUT_DIR} .
    DEPENDS javac_bindings
  )
endif()

# sample demo
# TODO: sample/src/Mvec.java is not for demo (to be packaged)
set(JAVA_MAIN "${CMAKE_CURRENT_SOURCE_DIR}/sample/src/Main.java")
add_custom_target(run_java
  COMMAND ${CMAKE_COMMAND} -E echo "Running demo…"
  COMMAND ${Java_JAVAC_EXECUTABLE} -cp ${JAVA_OUT_DIR} -d ${JAVA_OUT_DIR} ${JAVA_MAIN} "${CMAKE_CURRENT_SOURCE_DIR}/sample/src/Mvec.java"
  COMMAND ${CMAKE_COMMAND} -E env
          LD_LIBRARY_PATH=$<TARGET_FILE_DIR:cmake_project_name_original_case>
          java --enable-native-access=ALL-UNNAMED -cp ${JAVA_OUT_DIR} Main
  DEPENDS javac_bindings cmake_project_name_original_case
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
)