# === JavaBindings.cmake ===
# Configurable variables (cached)
# FIXME: hardcoded (use find_program() ?)
set(JEXTRACT_EXECUTABLE "/usr/share/jextract-22/bin/jextract"
    CACHE FILEPATH "Path to jextract")

set(MVEC_PUBLIC_HEADER "${CMAKE_CURRENT_SOURCE_DIR}/src/cmake_project_name_original_case/Mvec.h")

# Find Java (javac/jar)
find_package(Java COMPONENTS Development REQUIRED)
if (NOT EXISTS ${JEXTRACT_EXECUTABLE})
  message(FATAL_ERROR "jextract not found: ${JEXTRACT_EXECUTABLE}. set -DJEXTRACT_EXECUTABLE=...")
endif()

# Java build directories
set(JAVA_DIR ${CMAKE_CURRENT_BINARY_DIR}/java)
# sources generated by jextract
set(JAVA_SRC_DIR   ${JAVA_DIR}/src)
# class complitation outdir
set(JAVA_OUT_DIR   ${JAVA_DIR}/out)
file(MAKE_DIRECTORY ${JAVA_SRC_DIR})
file(MAKE_DIRECTORY ${JAVA_OUT_DIR})

# jextract: generates .java sources from flat 'extern C' cmake_project_name_original_case/Mvec.h
set(JAVA_PKG_DIR "${JAVA_SRC_DIR}/org/garamon/cmake_project_name_original_case")
set(JEXTRACT_JAVA "${JAVA_PKG_DIR}/Mvec_h.java")
add_custom_command(
  OUTPUT "${JEXTRACT_JAVA}"
  COMMAND ${CMAKE_COMMAND} -E echo "Running jextract…"
  COMMAND ${CMAKE_COMMAND} -E make_directory "${JAVA_SRC_DIR}"
  COMMAND "${JEXTRACT_EXECUTABLE}"
          -t org.garamon.cmake_project_name_original_case
          -l cmake_project_name_original_case
          --output "${JAVA_SRC_DIR}"
          "${MVEC_PUBLIC_HEADER}"
  # Optionnel: vérifier visuellement
  # COMMAND ${CMAKE_COMMAND} -E echo "Generated: ${JEXTRACT_JAVA}"
  DEPENDS cmake_project_name_original_case "${MVEC_PUBLIC_HEADER}"
  BYPRODUCTS "${JAVA_PKG_DIR}/Mvec_h.class"  # jextract ne génère pas .class, mais BYPRODUCTS ne gène pas
  VERBATIM
)
add_custom_target(jextract_bindings ALL DEPENDS "${JEXTRACT_JAVA}")

# copy templated Mvec.java (OO interface to Mvec_h to package directory)
set(MVEC_SRC     "${CMAKE_CURRENT_SOURCE_DIR}/src/cmake_project_name_original_case/java/Mvec.java")
set(MVEC_DST_DIR "${JAVA_SRC_DIR}/org/garamon/cmake_project_name_original_case")
set(MVEC_DST     "${MVEC_DST_DIR}/Mvec.java")

add_custom_command(
  OUTPUT "${MVEC_DST}" "${MVEC_DST_DIR}/.mvec_copied"
  COMMAND ${CMAKE_COMMAND} -E make_directory "${MVEC_DST_DIR}"
  COMMAND ${CMAKE_COMMAND} -E copy_if_different "${MVEC_SRC}" "${MVEC_DST}"
  COMMAND ${CMAKE_COMMAND} -E touch "${MVEC_DST_DIR}/.mvec_copied"
  DEPENDS "${MVEC_SRC}"
  COMMENT "Copying Mvec.java into generated source tree…"
  VERBATIM
)
add_custom_target(copy_mvec_java ALL DEPENDS "${MVEC_DST_DIR}/.mvec_copied")

# javac: compiles to ${JAVA_OUT_DIR}
set(MVEC_H_CLASS "${JAVA_OUT_DIR}/org/garamon/cmake_project_name_original_case/Mvec_h.class")
set(MVEC_CLASS   "${JAVA_OUT_DIR}/org/garamon/cmake_project_name_original_case/Mvec.class")

add_custom_command(
  OUTPUT "${MVEC_H_CLASS}" "${MVEC_CLASS}"
  COMMAND ${CMAKE_COMMAND} -E echo "Compiling Java…"
  COMMAND ${CMAKE_COMMAND} -E make_directory "${JAVA_OUT_DIR}"
  COMMAND "${Java_JAVAC_EXECUTABLE}"
          --source-path "${JAVA_SRC_DIR}"
          -cp "${JAVA_SRC_DIR}"
          -d "${JAVA_OUT_DIR}"
          "${JEXTRACT_JAVA}"
          "${MVEC_DST}"
  DEPENDS jextract_bindings copy_mvec_java
  VERBATIM
)
add_custom_target(javac_bindings ALL DEPENDS "${MVEC_H_CLASS}" "${MVEC_CLASS}")

# JAR
set(JAVA_JAR "${JAVA_OUT_DIR}/cmake_project_name_original_case.jar")
add_custom_target(jar
  COMMAND ${CMAKE_COMMAND} -E echo "Packaging JAR…"
  COMMAND ${Java_JAR_EXECUTABLE} cf ${JAVA_JAR} -C ${JAVA_OUT_DIR} .
  DEPENDS javac_bindings
)

# Javadoc
add_custom_command(
  OUTPUT "${JAVA_OUT_DIR}/cmake_project_name_original_case-javadoc.jar"
  COMMAND "${Java_JAVADOC_EXECUTABLE}"
          -d "${JAVA_OUT_DIR}/docs"
          -sourcepath "${JAVA_SRC_DIR}"
          org.garamon.cmake_project_name_original_case
  COMMAND "${Java_JAR_EXECUTABLE}" cf
          "${JAVA_OUT_DIR}/cmake_project_name_original_case-javadoc.jar"
          -C "${JAVA_OUT_DIR}/docs" .
  DEPENDS javac_bindings
  COMMENT "Building javadoc and javadoc.jar"
)
add_custom_target(javadoc_jar ALL
  DEPENDS "${JAVA_OUT_DIR}/cmake_project_name_original_case-javadoc.jar")

# sources jar
add_custom_command(
  OUTPUT "${JAVA_OUT_DIR}/cmake_project_name_original_case-sources.jar"
  COMMAND "${Java_JAR_EXECUTABLE}" cf
          "${JAVA_OUT_DIR}/cmake_project_name_original_case-sources.jar"
          -C "${JAVA_SRC_DIR}" .
  DEPENDS jextract_bindings copy_mvec_java
  COMMENT "Packaging cmake_project_name_original_case-sources.jar"
)
add_custom_target(sources_jar ALL
  DEPENDS "${JAVA_OUT_DIR}/cmake_project_name_original_case-sources.jar")

# sample demo
set(JAVA_MAIN "${CMAKE_CURRENT_SOURCE_DIR}/sample/src/Main.java")
add_custom_target(run_java
  COMMAND ${CMAKE_COMMAND} -E echo "Running demo…"
  COMMAND ${Java_JAVAC_EXECUTABLE} -cp ${JAVA_JAR} ${JAVA_MAIN}
  COMMAND ${CMAKE_COMMAND} -E env
          #LD_LIBRARY_PATH=$<TARGET_FILE_DIR:cmake_project_name_original_case>
          java --enable-native-access=ALL-UNNAMED -cp ${JAVA_JAR} ${JAVA_MAIN}
  DEPENDS jar
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
)

add_custom_target(all_java
    COMMENT "Build and run all Java-related targets"
)
add_dependencies(all_java run_java javadoc_jar sources_jar)